<?php
include ('fpdf/fpdf.php');
$pdf = new FPDF('L', 'mm', 'Letter');
$pdf->SetMargins(9, 10);
$pdf->SetAutoPageBreak(true, 5);
$alto = 3;
$tamFuente = 8;
$bor = 0;

$i = 0;
foreach ($afps as $afp):
	$pdf->AddPage();
	// debug($afp);
	// encabezado
	$pdf->SetFont('Courier', 'B', $tamFuente);
	$pdf->Cell(50, $alto, 'A.F.P. '.utf8_decode(strtoupper($afp['Afp']['nombre'])), $bor);
	$pdf->SetX(9);
	$pdf->Cell(0, $alto, 'PLANILLA DE PAGO DE COTIZACIONES PREVISIONALES Y DEPOSITOS DE AHORRO VOLUNTARIO', $bor, 0, 'C');
	$pdf->SetX(218);
	$pdf->SetFont('Courier', '', $tamFuente-2);
	$pdf->Cell(0, $alto, 'Nº SERIE DECLARACION', $bor);
	$pdf->SetX(258);
	$pdf->Cell(0, $alto, 'FOLIO', $bor, 1);
	$pdf->SetFont('Courier', 'B', $tamFuente);
	$pdf->Cell(0, $alto, 'FONDOS DE PENSIONES Y SEGURO DE CESANTIA', $bor, 1, 'C');
	$pdf->SetFont('Courier', '', $tamFuente-2);
	$pdf->Cell(0, $alto, '(SOLO PARA TRABAJADORES DEPENDIENTES)', $bor, 0, 'C');
	$pdf->Rect(215, 14, 33, 5);
	$pdf->Rect(252, 14, 20, 5);

	// sección i
	$pdf->ln();
	$pdf->SetFont('Courier', 'B', $tamFuente);
	$pdf->Cell(0, $alto, 'SECCION I: IDENTIFICACION DEL EMPLEADOR:', $bor, 1);
	$pdf->Cell(0, 0, '', 1);
	$pdf->ln(1);
	$pdf->SetFont('Courier', '', $tamFuente);
	$pdf->Cell(35, $alto, 'Razón Social:', $bor);
	$pdf->SetFont('Courier', 'B', $tamFuente);
	$pdf->Cell(70, $alto, utf8_decode($empresa['Empresa']['nombre']), $bor);
	$pdf->SetX(130);
	$pdf->SetFont('Courier', '', $tamFuente);
	$pdf->Cell(25, $alto, 'R.U.T.:', $bor);
	$pdf->SetFont('Courier', 'B', $tamFuente);
	$pdf->Cell(45, $alto, utf8_decode($empresa['Empresa']['rut']), $bor);
	$pdf->SetX(190);
	$pdf->SetFont('Courier', '', $tamFuente);
	$pdf->Cell(30, $alto, 'Cod. Act. Econ.:', $bor);
	$pdf->SetFont('Courier', 'B', $tamFuente);
	$pdf->Cell(45, $alto, utf8_decode($empresa['Empresa']['actividad_id']), $bor);
	$pdf->ln();
	$pdf->SetFont('Courier', '', $tamFuente);
	$pdf->Cell(35, $alto, 'Dirección:', $bor);
	$pdf->SetFont('Courier', 'B', $tamFuente);
	$pdf->Cell(70, $alto, utf8_decode($empresa['Empresa']['direccion'].', '.$empresa['Empresa']['ciudad']), $bor);
	$pdf->SetX(190);
	$pdf->SetFont('Courier', '', $tamFuente);
	$pdf->Cell(30, $alto, 'Teléfono:', $bor);
	$pdf->SetFont('Courier', 'B', $tamFuente);
	$pdf->Cell(45, $alto, utf8_decode($empresa['Empresa']['telefono']), $bor);
	$pdf->ln();
	$pdf->SetFont('Courier', '', $tamFuente);
	$pdf->Cell(35, $alto, 'Nombre Rep. Legal:', $bor);
	$pdf->SetFont('Courier', 'B', $tamFuente);
	$pdf->Cell(70, $alto, utf8_decode($empresa['Empresa']['rep_legal_nombre']), $bor);
	$pdf->SetX(130);
	$pdf->SetFont('Courier', '', $tamFuente);
	$pdf->Cell(25, $alto, 'R.U.T. Repr.:', $bor);
	$pdf->SetFont('Courier', 'B', $tamFuente);
	$pdf->Cell(45, $alto, utf8_decode($empresa['Empresa']['rep_legal_rut']), $bor);
	$pdf->SetX(190);
	$pdf->SetFont('Courier', '', $tamFuente);
	$pdf->Cell(30, $alto, 'Cambio Repr:', $bor);
	$pdf->Cell(25, $alto, 'Nº Trab.Dep.:', $bor);
	$pdf->Cell(10, $alto, $ntrab, $bor);
	
	// sección ii
	$pdf->ln($alto+2);
	$pdf->SetFont('Courier', 'B', $tamFuente);
	$pdf->Cell(0, $alto, 'SECCION II: DETALLE DE COTIZACIONES Y DEPOSITOS DE AHORRO VOLUNTARIO:', $bor, 1);
	$pdf->Cell(0, 0, '', 1);
	$pdf->ln(1);
	$pdf->SetFont('Courier', '', $tamFuente);
	$pdf->Cell(9, $alto, 'Nº', $bor, 0, 'C');
	$pdf->Cell(82, $alto, 'IDENTIFICACION DEL AFILIADO', $bor, 0, 'C');
	$pdf->Cell(54, $alto, 'FONDOS PENSIONES', $bor, 0, 'C');
	$pdf->Cell(54, $alto, 'SEGURO CESANTIA', $bor, 0, 'C');
	$pdf->Cell(63, $alto, 'MOVIMIENTOS REGISTROS DEL PERSONAL', $bor, 1, 'C');
	$y = $pdf->GetY();
	$pdf->MultiCell(9, $alto, "Sec.\n(1)", $bor, 'C');
	$pdf->SetXY(18, $y);
	$pdf->MultiCell(22, $alto, "RUT o CI\n(2)", $bor, 'C');
	$pdf->SetXY(18+22, $y);
	$pdf->MultiCell(60, $alto, "Ap.Paterno Ap.Materno Nombres\n(3)", $bor, 'C');
	$pdf->SetXY(18+22+60, $y);
	$pdf->MultiCell(18, $alto, "Remun.\nImpon.(4)", $bor, 'C');
	$pdf->SetXY(18+22+60+18, $y);
	$pdf->MultiCell(18, $alto, "Cotizac.\nOblig.(5)", $bor, 'C');
	$pdf->SetXY(18+22+60+18+18, $y);
	$pdf->MultiCell(18, $alto, "Dep. Cta.\nAhorro(6)", $bor, 'C');
	$pdf->SetXY(18+22+60+18+18+18, $y);
	$pdf->MultiCell(18, $alto, "Remun.\nImpon.(7)", $bor, 'C');
	$pdf->SetXY(18+22+60+18+18+18+18, $y);
	$pdf->MultiCell(18, $alto, "Cotizac.\nAfil.(8)", $bor, 'C');
	$pdf->SetXY(18+22+60+18+18+18+18+18, $y);
	$pdf->MultiCell(18, $alto, "Cotizac.\nEmpl.(9)", $bor, 'C');
	$pdf->SetXY(208, $y);
	$pdf->MultiCell(9, $alto, "Cod.", $bor, 'C');
	$pdf->SetXY(217, $y);
	$pdf->MultiCell(18, $alto, "Fecha\nInicio", $bor, 'C');
	$pdf->SetXY(217+18, $y);
	$pdf->MultiCell(18, $alto, "Fecha\nTérmino", $bor, 'C');
	$pdf->SetXY(217+18+18, $y);
	$pdf->MultiCell(18, $alto, "RUT Ent.\nPagadora", $bor, 'C');
	
	$pdf->Cell(0, 0, '', 1);
	$pdf->ln(1);
	$totalImponible = 0;
	$totalCotizOblig = 0;
	$totalApv = 0;
	$totalImponibleSeg = 0;
	$totalSegAfil = 0;
	$totalSegEmpl = 0;
	$nAfilPen = 0;
	$nAfilCes = 0;
	$j = 0;
	foreach ($empleados[$i] as $empleado):
		$pdf->Cell(9, $alto, $j+1, $bor, 0, 'C');
		$pdf->Cell(22, $alto, utf8_decode($empleado['Empleado']['rut']), $bor);
		$pdf->Cell(60, $alto, utf8_decode($empleado['Empleado']['apell_paterno'].' '.$empleado['Empleado']['apell_materno'].' '.$empleado['Empleado']['nombres']), $bor);
		$pdf->Cell(18, $alto, utf8_decode($empleado['Liquidacion']['imponible']), $bor, 0, 'R');
		$pdf->Cell(18, $alto, utf8_decode($empleado['Liquidacion']['cotiz_oblig']), $bor, 0, 'R');
		$pdf->Cell(18, $alto, utf8_decode($empleado['Liquidacion']['apv']), $bor, 0, 'R');
		if ($empleado['Liquidacion']['seg_empl'] != 0) {
			$pdf->Cell(18, $alto, utf8_decode($empleado['Liquidacion']['imponible']), $bor, 0, 'R');
			$totalImponibleSeg += $empleado['Liquidacion']['imponible'];
			$nAfilCes++;
		} else {
			$pdf->Cell(18, $alto, 0, $bor, 0, 'R');
		}
		$pdf->Cell(18, $alto, utf8_decode($empleado['Liquidacion']['seg_afil']), $bor, 0, 'R');
		$pdf->Cell(18, $alto, utf8_decode($empleado['Liquidacion']['seg_empl']), $bor, 0, 'R');
		$pdf->ln();
		$totalImponible += $empleado['Liquidacion']['imponible'];
		$totalCotizOblig += $empleado['Liquidacion']['cotiz_oblig'];
		$totalApv += $empleado['Liquidacion']['apv'];
		$totalSegAfil += $empleado['Liquidacion']['seg_afil'];
		$totalSegEmpl += $empleado['Liquidacion']['seg_empl'];
		$nAfilPen++;
		$j++;
	endforeach;
	$pdf->SetY(95);
	$pdf->SetFont('Courier', 'B', $tamFuente);
	$pdf->Cell(0, 0, '', 1);
	$pdf->ln(1);
	$pdf->SetX(70);
	$pdf->Cell(30, $alto, 'TOTAL PAGINA:', $bor);
	$pdf->Cell(18, $alto, $totalImponible, $bor, 0, 'R');
	$pdf->Cell(18, $alto, $totalCotizOblig, $bor, 0, 'R');
	$pdf->Cell(18, $alto, $totalApv, $bor, 0, 'R');
	$pdf->Cell(18, $alto, $totalImponibleSeg, $bor, 0, 'R');
	$pdf->Cell(18, $alto, $totalSegAfil, $bor, 0, 'R');
	$pdf->Cell(18, $alto, $totalSegEmpl, $bor, 0, 'R');
	$pdf->Cell(8, $alto, '', $bor);
	$pdf->Cell(43, $alto, 'TOTAL MOVIM. INFORMADOS:', $bor);
	$pdf->Cell(0, $alto, '0', $bor, 1, 'R');
	$pdf->SetX(100);
	$pdf->Cell(108, 0, '', 1);
	$pdf->SetX(259);
	$pdf->Cell(0, 0, '', 1);
	
	// sección iii
	$pdf->ln($alto);
	$pdf->Cell(0, $alto, 'SECCION III: RESUMEN DE COTIZACIONES Y DEPOSITOS:', $bor, 1);
	$pdf->Cell(0, 0, '', 1);
	$pdf->ln(1);
	$pdf->SetFont('Courier', '', $tamFuente);
	$y = $pdf->GetY();
	$pdf->Cell(65, $alto, 'SUBSECCION III.1 FONDO DE PENSIONES', $bor, 1);
	$pdf->Cell(38, $alto, 'DETALLE', $bor, 0, 'C');
	$pdf->Cell(9, $alto, 'COD.', $bor, 0, 'C');
	$pdf->Cell(18, $alto, 'VALORES', $bor, 1, 'C');
	$pdf->Cell(38, $alto, 'Cotización Obligatoria', $bor);
	$pdf->Cell(9, $alto, '01', $bor, 0, 'R');
	$pdf->Cell(18, $alto, $totalCotizOblig, $bor, 1, 'R');
	$pdf->Cell(38, $alto, 'Depósitos Cta. Ahorro', $bor);
	$pdf->Cell(9, $alto, '02', $bor, 0, 'R');
	$pdf->Cell(18, $alto, $totalApv, $bor, 1, 'R');
	$pdf->Cell(38, $alto, 'Subtotal a Pagar', $bor);
	$pdf->Cell(9, $alto, '03', $bor, 0, 'R');
	$pdf->Cell(18, $alto, $totalCotizOblig + $totalApv, $bor, 1, 'R');
	$pdf->Cell(38, $alto, '+ Reajuste F.Pensiones', $bor);
	$pdf->Cell(9, $alto, '04', $bor, 0, 'R');
	$pdf->Cell(18, $alto, '', $bor, 1, 'R');
	$pdf->Cell(38, $alto, '+ Intereses F.Pensiones', $bor);
	$pdf->Cell(9, $alto, '05', $bor, 0, 'R');
	$pdf->Cell(18, $alto, '', $bor, 1, 'R');
	$pdf->Cell(38, $alto, 'TOTAL PAGAR F.PENSIONES', $bor);
	$pdf->Cell(9, $alto, '10', $bor, 0, 'R');
	$pdf->Cell(18, $alto, $totalCotizOblig + $totalApv, $bor, 1, 'R');
	$pdf->SetXY(74, $y);
	$pdf->Cell(65, $alto, 'SUBSECCION III.2 A.F.P.', $bor, 1);
	$pdf->SetX(74);
	$pdf->Cell(38, $alto, 'DETALLE', $bor, 0, 'C');
	$pdf->Cell(9, $alto, 'COD.', $bor, 0, 'C');
	$pdf->Cell(18, $alto, 'VALORES', $bor, 1, 'C');
	$pdf->SetX(74);
	$pdf->Cell(38, $alto, '+ Recargo 20% ints.', $bor);
	$pdf->Cell(9, $alto, '56', $bor, 0, 'R');
	$pdf->Cell(18, $alto, '', $bor, 1, 'R');
	$pdf->SetX(74);
	$pdf->Cell(38, $alto, '+ Costos de Cobranzas', $bor);
	$pdf->Cell(9, $alto, '57', $bor, 0, 'R');
	$pdf->Cell(18, $alto, '', $bor, 1, 'R');
	$pdf->SetX(74);
	$pdf->Cell(38, $alto, 'TOTAL A PAGAR A.F.P.', $bor);
	$pdf->Cell(9, $alto, '60', $bor, 0, 'R');
	$pdf->Cell(18, $alto, '', $bor, 1, 'R');
	$pdf->SetXY(140, $y);
	$pdf->Cell(65, $alto, 'SUBSECCION III.3 FONDO DE CESANTIA', $bor, 1);
	$pdf->SetX(140);
	$pdf->Cell(38, $alto, 'DETALLE', $bor, 0, 'C');
	$pdf->Cell(9, $alto, 'COD.', $bor, 0, 'C');
	$pdf->Cell(18, $alto, 'VALORES', $bor, 1, 'C');
	$pdf->SetX(140);
	$pdf->Cell(38, $alto, 'Cotización Afiliado', $bor);
	$pdf->Cell(9, $alto, '11', $bor, 0, 'R');
	$pdf->Cell(18, $alto, $totalSegAfil, $bor, 1, 'R');
	$pdf->SetX(140);
	$pdf->Cell(38, $alto, 'Cotización Empleador', $bor);
	$pdf->Cell(9, $alto, '12', $bor, 0, 'R');
	$pdf->Cell(18, $alto, $totalSegEmpl, $bor, 1, 'R');
	$pdf->SetX(140);
	$pdf->Cell(38, $alto, 'Subtotal a Pagar Fondo', $bor);
	$pdf->Cell(9, $alto, '13', $bor, 0, 'R');
	$pdf->Cell(18, $alto, $totalSegAfil + $totalSegEmpl, $bor, 1, 'R');
	$pdf->SetX(140);
	$pdf->Cell(38, $alto, '+ Reajuste F. Cesantía', $bor);
	$pdf->Cell(9, $alto, '14', $bor, 0, 'R');
	$pdf->Cell(18, $alto, '', $bor, 1, 'R');	
	$pdf->SetX(140);
	$pdf->Cell(38, $alto, '+ Intereses F. Cesantía', $bor);
	$pdf->Cell(9, $alto, '15', $bor, 0, 'R');
	$pdf->Cell(18, $alto, '', $bor, 1, 'R');	
	$pdf->SetX(140);
	$pdf->Cell(38, $alto, 'TOTAL PAGAR F. CESANTIA', $bor);
	$pdf->Cell(9, $alto, '20', $bor, 0, 'R');
	$pdf->Cell(18, $alto, $totalSegAfil + $totalSegEmpl, $bor, 1, 'R');
	$pdf->SetXY(205, $y);
	$pdf->Cell(65, $alto, 'SUBSECCION III.4 A.F.C.', $bor, 1);
	$pdf->SetX(205);
	$pdf->Cell(38, $alto, 'DETALLE', $bor, 0, 'C');
	$pdf->Cell(9, $alto, 'COD.', $bor, 0, 'C');
	$pdf->Cell(18, $alto, 'VALORES', $bor, 1, 'C');
	$pdf->SetX(205);
	$pdf->Cell(38, $alto, 'Costos de Cobranzas', $bor);
	$pdf->Cell(9, $alto, '67', $bor, 0, 'R');
	$pdf->Cell(18, $alto, '', $bor, 1, 'R');
	$pdf->SetX(205);
	$pdf->Cell(38, $alto, 'TOTAL A PAGAR A.F.C.', $bor);
	$pdf->Cell(9, $alto, '70', $bor, 0, 'R');
	$pdf->Cell(18, $alto, '', $bor, 1, 'R');
	
	// sección iv
	$pdf->SetY(132);
	$pdf->SetFont('Courier', 'B', $tamFuente);
	$pdf->Cell(138, $alto, 'SECCION IV: ANTECEDENTES GENERALES:', $bor, 1);
	$pdf->Cell(138, 0, '', 1);
	$pdf->ln(1);
	$pdf->SetFont('Courier', '', $tamFuente);
	$pdf->Cell(138, $alto, 'TIPO DE INGRESO IMPONIBLE', $bor, 1);
	$y = $pdf->GetY();
	$pdf->Cell(85, $alto, 'Remuneraciones  Gratificaciones', $bor, 1);
	$pdf->Cell(85, $alto, 'Mes  (   )           (   )      Desde:', $bor);
	$pdf->SetX(21);
	$pdf->SetFont('Courier', 'B', $tamFuente);
	$pdf->Cell(5, $alto, 'X', $bor, 1);
	$pdf->SetFont('Courier', '', $tamFuente);
	$pdf->ln();
	$pdf->Cell(85, $alto, 'Periodo:                        Hasta:', $bor);
	$pdf->SetX(27);
	$pdf->SetFont('Courier', 'B', $tamFuente);
	$pdf->Cell(20, $alto, $session->read('mes').'/'.$session->read('ano'), $bor, 1);
	$pdf->SetFont('Courier', '', $tamFuente);
	$pdf->ln();
	$pdf->Cell(85, $alto, '1. NORMAL     (   )', $bor);
	$pdf->SetX(36);
	$pdf->SetFont('Courier', 'B', $tamFuente);
	$pdf->Cell(5, $alto, 'X', $bor, 1);
	$pdf->SetFont('Courier', '', $tamFuente);
	$pdf->Cell(85, $alto, '2. ATRASADA   (   )', $bor, 1);
	$pdf->Cell(85, $alto, '2. ADELANTADA (   )        F. Pago:', $bor, 1);
	$pdf->ln();
	$pdf->Cell(28, $alto, 'Nº Hojas Anexas: ', $bor);
	$pdf->SetFont('Courier', 'B', $tamFuente);
	$pdf->Cell(5, $alto, '0', $bor, 1);
	
	$pdf->SetXY(94, $y);
	$pdf->SetFont('Courier', '', $tamFuente);
	$pdf->MultiCell(26, $alto, "Total Remuner.\no Gratificac.\nFdos Pensiones", $bor, 'C');
	$pdf->SetFont('Courier', 'B', $tamFuente);
	$pdf->SetX(94);
	$pdf->Cell(26, $alto, $totalImponible, $bor, 1, 'C');
	$pdf->ln();
	$pdf->SetFont('Courier', '', $tamFuente);
	$pdf->SetX(94);
	$pdf->MultiCell(26, $alto, "Total Remuner.\no Gratificac.\nFondo Cesantía", $bor, 'C');
	$pdf->SetFont('Courier', 'B', $tamFuente);
	$pdf->SetX(94);
	$pdf->Cell(26, $alto, $totalImponibleSeg, $bor, 1, 'C');
	
	$pdf->SetXY(120, $y);
	$pdf->SetFont('Courier', '', $tamFuente);
	$pdf->MultiCell(26, $alto, "Nº Afiliados\nInformados\nFdos Pensiones", $bor, 'C');
	$pdf->SetFont('Courier', 'B', $tamFuente);
	$pdf->SetX(120);
	$pdf->Cell(26, $alto, $nAfilPen, $bor, 1, 'C');
	$pdf->ln();
	$pdf->SetFont('Courier', '', $tamFuente);
	$pdf->SetX(120);
	$pdf->MultiCell(26, $alto, "Nº Afiliados\nInformados\nFondo Cesantía", $bor, 'C');
	$pdf->SetFont('Courier', 'B', $tamFuente);
	$pdf->SetX(120);
	$pdf->Cell(26, $alto, $nAfilCes, $bor, 1, 'C');
	
	// sección v
	$pdf->SetXY(150, 132);
	$pdf->SetFont('Courier', 'B', $tamFuente);
	$pdf->Cell(120, $alto, 'SECCION V: ANTECEDENTES SOBRE EL PAGO:', $bor, 1);
	$pdf->SetX(150);
	$pdf->Cell(120, 0, '', 1);
	$pdf->ln(1);
	$pdf->SetFont('Courier', '', $tamFuente);
	$pdf->SetX(150); 
	$pdf->Cell(120, $alto, 'SUBSECCION V.1 - ANTECEDENTES SOBRE EL PAGO A LOS FONDOS DE PENSIONES', $bor, 1);
	$y = $pdf->GetY();
	$pdf->SetX(150); $pdf->Cell(60, $alto, 'Fondos de Pensiones', $bor, 1);
	$pdf->SetX(150); $pdf->Cell(60, $alto, 'Efect.(  )  Cheque (  ) Nº', $bor, 1);
	$pdf->ln();
	$pdf->SetX(150); $pdf->Cell(60, $alto, 'Banco             Plaza', $bor, 1);
	$pdf->ln();
	$pdf->SetX(150); $pdf->MultiCell(60, $alto, "GIRAR CHEQUE NOMINATIVO A FONDO\nDE PENSIONES ".utf8_decode(strtoupper($afp['Afp']['nombre'])), $bor, 'L');
	
	$pdf->SetXY(210, $y);
	$pdf->Cell(60, $alto, 'A.F.P.', $bor, 1);
	$pdf->SetX(210); $pdf->Cell(60, $alto, 'Efect.(  )  Cheque (  ) Nº', $bor, 1);
	$pdf->ln();
	$pdf->SetX(210); $pdf->Cell(60, $alto, 'Banco             Plaza', $bor, 1);
	$pdf->ln();
	$pdf->SetX(210); $pdf->MultiCell(60, $alto, "GIRAR CHEQUE NOMINATIVO A:\nAFP ".utf8_decode(strtoupper($afp['Afp']['nombre']))." S.A.", $bor, 'L');
	
	$pdf->ln();
	
	$pdf->SetX(150); 
	$pdf->Cell(120, $alto, 'SUBSECCION V.2 - ANTECEDENTES SOBRE EL PAGO A LOS FONDOS DE CESANTIA', $bor, 1);
	$y = $pdf->GetY();
	$pdf->SetX(150); $pdf->Cell(60, $alto, 'Fondos de Cesantía', $bor, 1);
	$pdf->SetX(150); $pdf->Cell(60, $alto, 'Efect.(  )  Cheque (  ) Nº', $bor, 1);
	$pdf->ln();
	$pdf->SetX(150); $pdf->Cell(60, $alto, 'Banco             Plaza', $bor, 1);
	$pdf->ln();
	$pdf->SetX(150); $pdf->MultiCell(60, $alto, "GIRAR CHEQUE NOMINATIVO A:\nFONDOS DE CESANTIA", $bor, 'L');
	
	$pdf->SetXY(210, $y);
	$pdf->Cell(60, $alto, 'A.F.C.', $bor, 1);
	$pdf->SetX(210); $pdf->Cell(60, $alto, 'Efect.(  )  Cheque (  ) Nº', $bor, 1);
	$pdf->ln();
	$pdf->SetX(210); $pdf->Cell(60, $alto, 'Banco             Plaza', $bor, 1);
	$pdf->ln();
	$pdf->SetX(210); $pdf->MultiCell(60, $alto, "GIRAR CHEQUE NOMINATIVO A:\nAFC CHILE S.A.", $bor, 'L');
	
	// firmas y timbres
	$pdf->SetXY(30, 205);
	$pdf->Cell(75, $alto, 'Firma del Empleador o Representante Legal', 'T', 0, 'C');
	$pdf->Cell(30);
	$pdf->Cell(45, $alto, 'VºBº Recepción y Cálculo', 'T', 0, 'C');
	$pdf->Cell(30);
	$pdf->Cell(45, $alto, 'VºBº y Timbre Cajero', 'T', 0, 'C');
	
	$i++;
endforeach;
$pdf->Output();
?>